// Vue/ProVue2/todo/src/App.vue
<template>
  <div id="app">
    <h4 class="bg-primary text-white text-center p-2">{{name}}'s To Do List</h4>
    <div class="container-fluid p-4">
      
      <div class="row" v-if="filteredTasks.length == 0">
        <div class="col text-center">
          <b>Nothing to do. Hurrah!</b>
        </div>
      </div>
      <template v-else>
        <div class="row">
          <div class="col font-weight-bold">Task</div>
          <div class="col-2 font-weight-bold">Done</div>
        </div>
        <div class="row" v-for="t in filteredTasks" v-bind:key="t.action">
          <div class="col">{{t.action}}</div>
          <div class="col-2 text-center">
            <input type="checkbox" v-model="t.done" class="form-check-input">
          </div>
        </div>
      </template>

      <div class="row py-2">
        <div class="col">
          <input v-model="newItemText" class="form-control">
        </div>
        <div class="col-2">
          <button class="btn btn-primary" v-on:click="addNewTodo">Add</button>
        </div>
      </div>

      <div class="row bg-secondary py-2 mt-2 text-white">
        <div class="col text-center">
          <input type="checkbox" v-model="hideCompleted" class="form-check-input">
          <label class="form-check-label font-weight-bold">Hide completed tasks</label>
        </div>
        <div class="col text-center">
          <button class="btn btn-sm btn-warning" v-on:click="deleteCompleted">Delete Completed</button>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "app",
  data() {
    return {
      name: "Adam",
      // tasks: [
      //   { action: "Buy Flowers", done: false },
      //   { action: "Get Shoes", done: false },
      //   { action: "Collect Tickets", done: true },
      //   { action: "Call Joe", done: false }
      // ],
      tasks: [],
      hideCompleted: false,
      newItemText: ""
    };
  },
  computed: {
    filteredTasks() {
      return this.hideCompleted ? this.tasks.filter(t => !t.done) : this.tasks;
    }
  },
  methods: {
    addNewTodo() {
      this.tasks.push({
        action: this.newItemText,
        done: false
      });
      //alert(this.newItemText);
      this.storeData();
      this.newItemText = "";
    },
    storeData() {
      localStorage.setItem("todos", JSON.stringify(this.tasks));
    },
    deleteCompleted() {
      this.tasks = this.tasks.filter(t => !t.done);
      this.storeData();
    }
  },
  created() {
    //localStorage.setItem("todos", JSON.stringify(this.tasks));
    let data = localStorage.getItem("todos");
    if (data != null) {
      //alert(data);
      this.tasks = JSON.parse(data);
    }
  }
};
</script>

// React/ProReact16/todo/src/App.js
import React, { Component } from 'react';
// import logo from './logo.svg';
// import './App.css';

// class App extends Component {
//   render() {
//     return (
//       <div className="App">
//         <header className="App-header">
//           <img src={logo} className="App-logo" alt="logo" />
//           <p>
//             Edit <code>src/App.js</code> and save to reload.
//           </p>
//           <a
//             className="App-link"
//             href="https://reactjs.org"
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             Learn React
//           </a>
//         </header>
//       </div>
//     );
//   }
// }

// export default App;

export default class App extends Component {

  constructor(props) {
    super(props);
    this.state = {
      userName: "Adam",
      todoItems: [
        { action: "Buy Flowers", done: false },
        { action: "Get Shoes", done: false },
        { action: "Collect Tickets", done: true },
        { action: "Call Joe", done: false }
      ],
      newItemText: ""
    }
  }

  updateNewTextValue = (event) => {
    this.setState({ newItemText: event.target.value });
  }

  createNewTodo = () => {
    if (!this.state.todoItems.find(item => item.action === this.state.newItemText)) {
      this.setState({
        todoItems: [
          ...this.state.todoItems,
          { action: this.state.newItemText, done: false }
        ],
        newItemText: ""
      });
    }
  }

  toggleTodo = (todo) => this.setState({ todoItems: this.state.todoItems.map(item => item.action === todo.action ? { ...item, done: !item.done } : item) })

  todoTableRows = () => this.state.todoItems.map(item =>
    <tr key={item.action}>
      <td>
        {item.action}
      </td>
      <td>
        <input type="checkbox" checked={item.done} onChange={() => this.toggleTodo(item)} />
      </td>
    </tr>
  );

  changeStateData = () => {
    this.setState(
      { userName: this.state.userName === "Adam" ? "Bob" : "Adam" }
    )
  }


  render = () =>
    <div>
      <h4 className="bg-primary text-white text-center p-2">
        {this.state.userName}'s To Do List
        ({this.state.todoItems.filter(t => !t.done).length} items to do)
      </h4>
      <div className="container-fluid">
        <div className="my-1">
          <input className="form-control" value={this.state.newItemText} onChange={this.updateNewTextValue} />
          <button className="btn btn-primary mt-1" onClick={this.createNewTodo}>Add</button>
        </div>
      </div>
      <table className="table table-striped table-bordered">
        <thead>
          <tr>
            <th>Description</th>
            <th>Done</th>
          </tr>
        </thead>
        <tbody>{this.todoTableRows()}</tbody>
      </table>
      <button className="btn btn-primary m-s" onClick={this.changeStateData}>
        Change
      </button>
    </div>


  // render() {
  //   return (
  //     <div>
  //       <h4 className="bg-primary text-white text-center p-2">
  //         {this.state.userName}'s To Do List
  //       </h4>
  //       <button className="btn btn-primary m-s" onClick = {this.changeStateData}>
  //         Change
  //       </button>
  //     </div>
  //   );
  // }

}
